on: push
jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        config: ./markdownlint-config.json
        ignore: ./node_modules
        args: './**/*.md'
